title: "Blogs "
author: "Author"
description: "desc"

email: "example@mail.com"
github_username: "0dragoish"
rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other

theme: "minima"
